# Generated by Django 5.2 on 2025-04-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('IM', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('hr', 'Conseiller RH'), ('employee', 'Employé')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Freelance', 'Freelance')], max_length=50)),
            ],
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='HrAdvisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('department', models.CharField(choices=[('Recrutement', 'Recrutement'), ('Formation', 'Formation'), ('Relations sociales', 'Relations sociales'), ('Développement', 'Développement des talents'), ('Paie', 'Rémunération'), ('SSCT', 'Santé, Sécurité et Conditions de travail')], max_length=50)),
            ],
            bases=('users.user',),
        ),
    ]
